apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432 # or port name on container, `postgres`
#  type: ClusterIP  # ClusterIP | NodePort | LoadBalancer | None (headless service)