name: Build hello app

on:
  push:
    paths:
      - .github/workflows/*
      - apps/hello/*
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        name: Checkout
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./apps/hello
          push: true
          tags: ghcr.io/bevy-city/kubernetes-play-party/hello:latest